//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KT2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHUTHU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHUTHU()
        {
            this.CHITIETDATPHONG = new HashSet<CHITIETDATPHONG>();
        }
    
        public string MaPhuThu { get; set; }
        public string TenPhuThu { get; set; }
        public Nullable<double> GiaPT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDATPHONG> CHITIETDATPHONG { get; set; }
    }
}
