CREATE DATABASE QL_Karaoke_KT2;
GO

USE QL_Karaoke_KT2;
GO

CREATE TABLE LOAIPHONG (
    MaNhom VARCHAR(10) PRIMARY KEY,
    TenNhom NVARCHAR(100) NOT NULL
);

CREATE TABLE PHONG (
    MaPhong VARCHAR(10) PRIMARY KEY,
    TenPhong NVARCHAR(100) NOT NULL,
    SucChua INT,
    GiaPhong FLOAT,
    KieuPhong INT, 
    MaNhom VARCHAR(10),
    CONSTRAINT FK_Phong_LoaiPhong FOREIGN KEY (MaNhom) REFERENCES LOAIPHONG(MaNhom)
);

CREATE TABLE KHACHHANG (
    MaKhachHang VARCHAR(10) PRIMARY KEY,
    TenKH NVARCHAR(100) NOT NULL,
    SoDT VARCHAR(15)
);

CREATE TABLE PHUTHU (
    MaPhuThu VARCHAR(10) PRIMARY KEY,
    TenPhuThu NVARCHAR(100) NOT NULL,
    GiaPT FLOAT
);

CREATE TABLE DATPHONG (
    MaDatPhong INT IDENTITY(1,1) PRIMARY KEY, 
    MaPh VARCHAR(10),
    MaKH VARCHAR(10),
    NgayDat DATETIME,
    NgayTra DATETIME,
    CONSTRAINT FK_DatPhong_Phong FOREIGN KEY (MaPh) REFERENCES PHONG(MaPhong),
    CONSTRAINT FK_DatPhong_KhachHang FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKhachHang)
);

CREATE TABLE CHITIETDATPHONG (
    MaCT VARCHAR(10) PRIMARY KEY,
    MaDP INT, 
    MaPT VARCHAR(10),
    SL INT,
    CONSTRAINT FK_CTDP_DatPhong FOREIGN KEY (MaDP) REFERENCES DATPHONG(MaDatPhong),
    CONSTRAINT FK_CTDP_PhuThu FOREIGN KEY (MaPT) REFERENCES PHUTHU(MaPhuThu)
);
GO

INSERT INTO LOAIPHONG (MaNhom, TenNhom) VALUES
('T1', N'Tầng 1'),
('T2', N'Tầng 2'),
('T3', N'Tầng 3');

INSERT INTO PHONG (MaPhong, TenPhong, SucChua, GiaPhong, KieuPhong, MaNhom) VALUES
('P01', N'Phòng VIP', 10, 150000, 2, 'T1'),
('P02', N'Phòng Thường', 8, 100000, 1, 'T2'),
('A1002', N'Phòng VIP 2', 20, 300000, 2, 'T1'),
('A1003', N'Phòng Thường lớn', 20, 200000, 1, 'T1');

INSERT INTO KHACHHANG (MaKhachHang, TenKH, SoDT) VALUES
('KH01', N'Nguyễn Văn A', '0901234567'),
('KH02', N'Trần Thị B', '0912345678');

INSERT INTO PHUTHU (MaPhuThu, TenPhuThu, GiaPT) VALUES
('PT01', N'Bia Tiger', 20000),
('PT02', N'Nước ngọt', 15000),
('PT03', N'Trái cây dĩa', 150000);

INSERT INTO DATPHONG (MaPh, MaKH, NgayDat, NgayTra) VALUES
('P01', 'KH01', '2024-05-26 13:00:00', '2024-05-26 15:00:00'),
('P02', 'KH02', '2024-05-26 19:00:00', '2024-05-26 22:00:00');

INSERT INTO CHITIETDATPHONG (MaCT, MaDP, MaPT, SL) VALUES
('CT01', 1, 'PT01', 5),
('CT02', 1, 'PT02', 2),
('CT03', 2, 'PT03', 1);
GO