-- Tạo Database (Nếu bạn đã có DB rồi thì bỏ qua 3 dòng này)
CREATE DATABASE QL_Kho;
GO
USE QL_Kho;
GO

-- 1. Bảng LOAISANPHAM
CREATE TABLE LOAISANPHAM (
    MALOAISANPHAM VARCHAR(20) PRIMARY KEY,
    TENLOAISANPHAM NVARCHAR(100) NOT NULL
);

-- 2. Bảng SANPHAM
CREATE TABLE SANPHAM (
    MASANPHAM VARCHAR(20) PRIMARY KEY,
    TENSANPHAM NVARCHAR(100) NOT NULL,
    MALOAISANPHAM VARCHAR(20),
    DONGIA DECIMAL(18, 0),
    FOREIGN KEY (MALOAISANPHAM) REFERENCES LOAISANPHAM(MALOAISANPHAM)
);

-- 3. Bảng TONKHO_NGAY
CREATE TABLE TONKHO_NGAY (
    MASANPHAM VARCHAR(20) PRIMARY KEY,
    SOLUONGTON INT DEFAULT 0,
    FOREIGN KEY (MASANPHAM) REFERENCES SANPHAM(MASANPHAM)
);

-- 4. Bảng NHACUNGCAP
CREATE TABLE NHACUNGCAP (
    MANCC VARCHAR(20) PRIMARY KEY,
    TENNCC NVARCHAR(100) NOT NULL,
    DIACHI NVARCHAR(200)
);

-- 5. Bảng NHANVIEN
CREATE TABLE NHANVIEN (
    MaNV VARCHAR(20) PRIMARY KEY,
    TenNV NVARCHAR(100) NOT NULL,
    NamSinh INT,
    DienThoai VARCHAR(15),
    Email VARCHAR(100),
    MatKhau VARCHAR(50) NOT NULL,
    VaiTro NVARCHAR(50)
);

-- 6. Bảng PHIEUNHAP
CREATE TABLE PHIEUNHAP (
    MAPHIEUNHAP VARCHAR(20) PRIMARY KEY,
    MANCC VARCHAR(20),
    NGAYNHAP DATE,
    THANHTIEN DECIMAL(18, 0),
    MANV VARCHAR(20),
    FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP(MANCC),
    FOREIGN KEY (MANV) REFERENCES NHANVIEN(MaNV)
);

-- 7. Bảng CHITIETPHIEUNHAP
CREATE TABLE CHITIETPHIEUNHAP (
    MAPHIEUNHAP VARCHAR(20),
    MASANPHAM VARCHAR(20),
    DONGIA DECIMAL(18, 0),
    SOLUONG INT,
    PRIMARY KEY (MAPHIEUNHAP, MASANPHAM),
    FOREIGN KEY (MAPHIEUNHAP) REFERENCES PHIEUNHAP(MAPHIEUNHAP),
    FOREIGN KEY (MASANPHAM) REFERENCES SANPHAM(MASANPHAM)
);
GO

---------------------------------------------------
-- CHÈN DỮ LIỆU MẪU (INSERT DATA)
---------------------------------------------------

-- Thêm Nhân viên (Mật khẩu chung là '123' cho dễ test bài 1)
INSERT INTO NHANVIEN (MaNV, TenNV, NamSinh, DienThoai, Email, MatKhau, VaiTro) VALUES
('NV01', N'Nguyễn Văn Hùng', 1990, '0901234567', 'hung@gmail.com', '123', N'Quản lý'),
('NV02', N'Trần Thị Lan', 1995, '0912345678', 'lan@gmail.com', '123', N'Nhân viên kho'),
('NV03', N'Phạm Thị Hạnh', 1998, '0923456789', 'hanh@gmail.com', '123', N'Nhân viên bán hàng');

-- Thêm Loại sản phẩm
INSERT INTO LOAISANPHAM (MALOAISANPHAM, TENLOAISANPHAM) VALUES
('TV', N'Smart TV'),
('ML', N'Máy lạnh'),
('TL', N'Tủ lạnh');

-- Thêm Sản phẩm
INSERT INTO SANPHAM (MASANPHAM, TENSANPHAM, MALOAISANPHAM, DONGIA) VALUES
('SP01', N'Smart TV Samsung 55 inch 4K', 'TV', 15000000),
('SP02', N'Máy lạnh Panasonic 1HP', 'ML', 9000000),
('SP03', N'Tủ lạnh Samsung Inverter 360L', 'TL', 12000000),
('SP04', N'Smart TV LG 50 inch 4K', 'TV', 11000000);

-- Thêm Tồn kho
INSERT INTO TONKHO_NGAY (MASANPHAM, SOLUONGTON) VALUES
('SP01', 50),
('SP02', 30),
('SP03', 20),
('SP04', 15);

-- Thêm Nhà cung cấp
INSERT INTO NHACUNGCAP (MANCC, TENNCC, DIACHI) VALUES
('NCC01', N'Điện máy Chợ Lớn', N'Quận 5, TP.HCM'),
('NCC02', N'Thiên Hòa', N'Quận 10, TP.HCM'),
('NCC03', N'LG Electronics Việt Nam', N'KCN Tràng Duệ, Hải Phòng');

-- Thêm Phiếu nhập
INSERT INTO PHIEUNHAP (MAPHIEUNHAP, MANCC, NGAYNHAP, THANHTIEN, MANV) VALUES
('PN000001', 'NCC01', '2025-12-20', 150000000, 'NV02'),
('PN000002', 'NCC02', '2025-12-21', 180000000, 'NV02');

-- Thêm Chi tiết phiếu nhập
INSERT INTO CHITIETPHIEUNHAP (MAPHIEUNHAP, MASANPHAM, DONGIA, SOLUONG) VALUES
('PN000001', 'SP01', 15000000, 10),
('PN000002', 'SP02', 9000000, 20);
GO